"""initial documents and metrics migration

Revision ID: d8052f692db3
Revises: 
Create Date: 2025-12-17 06:04:37.055641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8052f692db3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_processing_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_processing_run_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_processing_runs_id', sa.String(), nullable=False),
    sa.Column('extraction_completeness_pct', sa.Float(), nullable=True),
    sa.Column('field_fill_rate', sa.Float(), nullable=True),
    sa.Column('filled_fields_count', sa.Integer(), nullable=True),
    sa.Column('extracted_field_efficiency', sa.Float(), nullable=True),
    sa.Column('llm_token_cost', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('document_run_processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_processing_runs_id'], ['document_processing_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_processing_run_metrics_document_processing_runs_id'), 'document_processing_run_metrics', ['document_processing_runs_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_processing_run_metrics_document_processing_runs_id'), table_name='document_processing_run_metrics')
    op.drop_table('document_processing_run_metrics')
    op.drop_table('document_processing_runs')
    # ### end Alembic commands ###


